<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://www.eclipse.org/fennec/m2m/qvto/trace/1.0"
    nsPrefix="trace">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="complianceLevel" value="21.0"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="basePackage" value="org.eclipse.fennec.m2m.model"/>
    <details key="resource" value="XMI"/>
    <details key="copyrightText" value="******************************************************************&#xA;Copyright (c) 2026 Contributors to the Eclipse Foundation.&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;  Data In Motion Consulting - initial implementation&#xA;******************************************************************"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="EDirectionKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Direction kind for trace parameter values: IN, INOUT, or OUT."/>
    </eAnnotations>
    <eLiterals name="IN"/>
    <eLiterals name="INOUT" value="1"/>
    <eLiterals name="OUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Root container for all trace records of a transformation execution."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceRecords" upperBound="-1"
        eType="#//TraceRecord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceRecordMap" upperBound="-1"
        eType="#//MappingOperationToTraceRecordMapEntry" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceToTraceRecordMap"
        upperBound="-1" eType="#//ObjectToTraceRecordMapEntry" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetToTraceRecordMap"
        upperBound="-1" eType="#//ObjectToTraceRecordMapEntry" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceRecord">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A single trace record capturing one mapping execution: which mapping, its context, parameters, and results."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingOperation" lowerBound="1"
        eType="#//EMappingOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//EMappingContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        eType="#//EMappingParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//EMappingResults" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMappingOperation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Serializable description of a mapping operation in a trace record."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeMappingOperation"
        lowerBound="1" eType="ecore:EClass qvtoperational.ecore#//MappingOperation"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMappingContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Context (self) parameter value of a trace record."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//VarParameterValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMappingParameters">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Input/output parameter values of a trace record."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//VarParameterValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMappingResults">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Result parameter values of a trace record."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" upperBound="-1"
        eType="#//VarParameterValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarParameterValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named, typed parameter value in a trace record."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//EDirectionKind"
        defaultValueLiteral="IN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//EValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A trace value: can be a primitive, model element reference, or collection of values."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oclObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" upperBound="-1"
        eType="#//EValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETuplePartValue" eSuperTypes="#//EValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named tuple part value extending EValue with name and nested value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//EValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingOperationToTraceRecordMapEntry"
      instanceClassName="java.util.Map$Entry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Map entry: MappingOperation → list of TraceRecords."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="ecore:EClass qvtoperational.ecore#//MappingOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//TraceRecord"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectToTraceRecordMapEntry" instanceClassName="java.util.Map$Entry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Map entry: Java Object → list of TraceRecords."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//TraceRecord"/>
  </eClassifiers>
</ecore:EPackage>
