name: Dependency Review

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: eclipse-fennec/.github/.github/workflows/reusable-dependency-review.yml@5a1a919f7f7ca9dd4c13cbeb5bca6735c4d8ecb7 # v1.2.1
